version: '3.8'

services:
  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "5000:5000"

  user-service:
    build: ./backend/user-service
    ports:
      - "5001:5001"
    depends_on:
      - redis

  movie-service:
    build: ./backend/movie-service
    ports:
      - "5003:5003"

  review-service:
    build: ./backend/review-service
    ports:
      - "5002:5002"

  redis:
    image: redis
    ports:
      - "6379:6379"

  addreview-app:
    build: ./frontend/addReview-app
    ports:
      - "3002:3002"

  auth-app:
    build: ./frontend/auth-app
    ports:
      - "3000:3000"

  container-app:
    build: ./frontend/container-app
    ports:
      - "5173:5173"

  home-app:
    build: ./frontend/home-app
    ports:
      - "3001:3001"

  profile-app:
    build: ./frontend/profile-app
    ports:
      - "3004:3004"

  shared-components:
    build: ./frontend/shared-components
    ports:
      - "3010:3010"

  yourreview-app:
    build: ./frontend/yourreview-app
    ports:
      - "3003:3003"

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
